name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    
    steps:
      - name : "Community label"
        uses: label-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
            
